version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  cloudconfig:
    build:
      context: .
      dockerfile: CloudConfig/Dockerfile
    ports:
      - "8888:8888"
  
  produit:
    build:
      context: .
      dockerfile: microservice/produit/Dockerfile
    ports:
      - "8095:8095"

  eureka:
    build:
      context: .
      dockerfile: Eureka/Dockerfile
    ports:
      - "8761:8761"